### PR TITLE
[fix] link zlib statically, with better test

### LINKED ISSUE #37: Binary not static
Hi,

for a while i was using rust-musl-builder as a git submodule. So I did not update. 
I tried to update to master and now my binary is no longer static. (same with the dockerhub version)

```
» file target/x86_64-unknown-linux-musl/release/fw                                                                                                                                                                                                     
target/x86_64-unknown-linux-musl/release/fw: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld64.so.1, BuildID[sha1]=bc7437143885536c8640f165e4fccbc4fdaf2ff9, with debug_info, not stripped
```
Here is my repo https://github.com/brocode/fw

With commit `8ea04b5f166b18dfa4bd5c49c771e2598284f87f` everything works fine.

### PR DESCRIPTION
**Pull request by mriehl**
See #41 #38 

Fixes #37

This is basically #38 with the tests encoded using `cargo new` semantics (no docker volume for the project)

### CODE REVIEW

**Comment by mriehl** [comment]
Here's the travis job: https://travis-ci.org/mriehl/rust-musl-builder/jobs/358272959
I hope I didn't break the travis config while refactoring, standing by..

**Comment by mriehl** [comment]
https://travis-ci.org/mriehl/rust-musl-builder/builds/358272958 still green

**Comment by mriehl** [comment]
Note that I tested the "file check" locally too. This was missing as pointed out by @bomgar because if the file doesn't exist, `ldd` also fails (with the same exit code).
There's a bit of duplication in the file path, but using a variable is such a fuckery in the multiline string (especially since I wanted to split it into path components because the test is slow as hell so getting tree like output is critical imho)

**Comment by bomgar** [comment]
@emk isn't this exactly what you wanted?

**Comment by emk** [comment]
Merged after overhauling the tests. Thank you!

**Pull request merged**
